### PR TITLE
Add-Caesar_Cipher_Algorithm

### PR DESCRIPTION
**Pull request by SayaniG371**
#21 Issue Solved

### CODE REVIEW

**Comment by SayaniG371** [comment]
@tarunjain1st  Please review this PR! 
Can you please add Hacktoberfest to your repo Topic or else our PR's will not be eligible! Thanks again.

**Comment by tarunjain1st** [comment]
i have added label in this one

**Comment by SayaniG371** [comment]
Sir, I am truly sorry for troubling you again. but in the Hacktoberfest website, it is still showing that this repo is not participating is hacktoberfest, that's why our PR's are not being ineligible sir. Sir can you please go to the CODE tab in this repo and then in about section, to the settings icon and add a topic as Hacktoberfest. Thank you sir !

**Comment by tarunjain1st** [comment]
hey can you forward me that link ?

**Comment by SayaniG371** [comment]
Sir the hacktoberfest link?

**Comment by SayaniG371** [comment]
Its done sir , thank you. My PR's are eligible

**Comment by tarunjain1st** [comment]
Hey @SayaniG371 can you tell me where we can check that this repository is eligible or not

**Comment by SayaniG371** [comment]
Sir in my Hacktoberfest Profile , My PR was marked with an exclamatory icon. And there only it was written that the exclamatory icon is for ineligible repository. The repo can be made eligible by adding topic as Hacktoberfest. That's where I found it sir

**Comment by SayaniG371** [comment]
When you added the topic , My PR is in review period now. So this repo is eligible now sir

**Comment by tarunjain1st** [comment]
can you send a screenshot of before and after

**Comment by tarunjain1st** [comment]
or just send the screenshot so that i can tell other also to make changes in repo

**Comment by SayaniG371** [comment]
Sure sir, these are the ss
(Before you added the topic the caesar cipher algorithm was showing '!' instead of the clock icon

Screenshot (34)

Screenshot (32)

**Comment by tarunjain1st** [comment]
OKAY

**Comment by tarunjain1st** [comment]
Thanks @SayaniG371 for support it is very helpful for us :)

**Pull request merged**
